import "dotenv/config";
import { EventSource } from "eventsource";
if (typeof globalThis.EventSource === "undefined") {
  globalThis.EventSource = EventSource;
}
import {
  Wallet,
  SingleKey,
  MnemonicIdentity,
  InMemoryWalletRepository,
  InMemoryContractRepository,
} from "@arkade-os/sdk";
import { generateMnemonic, mnemonicToSeedSync, validateMnemonic } from "@scure/bip39";
import { wordlist } from "@scure/bip39/wordlists/english";
import { HDKey } from "@scure/bip32";
import { hex } from "@scure/base";
import { writeFileSync, existsSync, chmodSync } from "node:fs";
import { resolve } from "node:path";

const LEGACY_DERIVATION_PATH = "m/44'/1237'/0'";

const network = process.env.ARK_NETWORK || "bitcoin";
const arkServerUrl =
  process.env.ARK_SERVER_URL || "https://arkade.computer";

async function main() {
  let mnemonic;

  if (process.env.ARK_MNEMONIC) {
    console.log("Importing existing wallet from ARK_MNEMONIC...\n");
    mnemonic = process.env.ARK_MNEMONIC;
    if (!validateMnemonic(mnemonic, wordlist)) {
      throw new Error("Invalid BIP39 mnemonic: checksum failed or contains invalid words");
    }
  } else {
    console.log("No ARK_MNEMONIC found. Generating new wallet...\n");
    mnemonic = generateMnemonic(wordlist);
  }

  const isMainnet = network === "bitcoin";
  const storageOpts = () => ({
    walletRepository: new InMemoryWalletRepository(),
    contractRepository: new InMemoryContractRepository(),
  });

  // Always use BIP-86 as the primary wallet
  const identity = MnemonicIdentity.fromMnemonic(mnemonic, { isMainnet });
  const wallet = await Wallet.create({
    identity, arkServerUrl, storage: storageOpts(),
  });

  const arkAddress = await wallet.getAddress();
  const boardingAddress = await wallet.getBoardingAddress();

  console.log("=== Arkade Wallet ===");
  console.log("Network:         ", network);
  console.log("Server:          ", arkServerUrl);
  console.log("Derivation:       m/86'/0'/0'/0/0 (BIP-86, SDK standard)");
  console.log("Ark Address:     ", arkAddress);
  console.log("Boarding Address:", boardingAddress);

  // Check for legacy funds when importing an existing mnemonic
  if (process.env.ARK_MNEMONIC) {
    const seed = mnemonicToSeedSync(mnemonic);
    const master = HDKey.fromMasterSeed(seed);
    const legacyKey = master.derive(LEGACY_DERIVATION_PATH).deriveChild(0).deriveChild(0);
    const legacyIdentity = SingleKey.fromHex(hex.encode(legacyKey.privateKey));
    const legacyWallet = await Wallet.create({
      identity: legacyIdentity, arkServerUrl, storage: storageOpts(),
    });
    const legacyBalance = await legacyWallet.getBalance();

    if (legacyBalance.total > 0n) {
      const legacyAddress = await legacyWallet.getAddress();
      console.warn(
        "\n=== WARNING: Legacy Funds Detected ===\n" +
        `  Legacy balance: ${legacyBalance.total.toString()} sats\n` +
        `  Legacy path:    m/44'/1237'/0'/0/0\n` +
        `  Legacy address: ${legacyAddress}\n` +
        "  This path is deprecated and VTXOs will NOT be auto-renewed.\n" +
        "  Migrate funds by sending from the legacy address to your BIP-86 address:\n" +
        `  ${arkAddress}\n` +
        "  Use ArkadeAgent.migrateLegacyFunds() for automatic migration."
      );
    }
  }

  if (!process.env.ARK_MNEMONIC) {
    // Write mnemonic to .env file instead of stdout to prevent leakage
    // via logs, CI pipelines, screen sharing, or shell history.
    const envPath = resolve(process.cwd(), ".env");
    const envContent =
      `# Generated by wallet-setup.js — NEVER commit this file\n` +
      `ARK_MNEMONIC=${mnemonic}\n` +
      `ARK_SERVER_URL=${arkServerUrl}\n` +
      `ARK_NETWORK=${network}\n`;

    if (existsSync(envPath)) {
      // Don't overwrite existing .env — write to .env.new instead
      const newPath = resolve(process.cwd(), ".env.new");
      writeFileSync(newPath, envContent, { mode: 0o600 });
      chmodSync(newPath, 0o600);
      console.log(`\n=== Wallet Generated ===`);
      console.log(`Mnemonic written to: ${newPath} (owner-read-write only)`);
      console.log("Existing .env was NOT overwritten.");
      console.log("Merge .env.new into .env manually, then delete .env.new");
    } else {
      writeFileSync(envPath, envContent, { mode: 0o600 });
      chmodSync(envPath, 0o600);
      console.log(`\n=== Wallet Generated ===`);
      console.log(`Mnemonic written to: ${envPath} (owner-read-write only)`);
    }

    console.log("\nBack up your mnemonic offline (write it down).");
    console.log("If you lose it, your funds are gone permanently.");
    console.log("Verify .env is in .gitignore before committing anything.");
  }
  process.exit(0);
}

main().catch((err) => {
  console.error("Error:", err.message);
  process.exit(1);
});
